version: '3.8'
services:
  dashboard:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - ALERT_EMAIL_TO=${ALERT_EMAIL_TO}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM=${TWILIO_FROM}
      - TWILIO_TO=${TWILIO_TO}
      - DH_DB=/data/device_data.db
    volumes:
      - data:/data
volumes:
  data: